spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9200
      scheme: http
      maxRetryTimeoutMillis: 10000
      socketTimeout: 10000
      header: key:value,key2:value2
